services:
  # Backend API Service
  - type: web
    name: rental-system-api
    runtime: python3
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: "3.11.0"
    
  # Frontend Static Site
  - type: static
    name: rental-system-frontend
    buildCommand: "echo 'No build required'"
    staticPublishPath: "./fronted"
    plan: free
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
